version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - python manage.py collectstatic --no-input
      - python manage.py migrate
  post_build:
    commands:
      - echo "Build completed on `date`"
